### ISSUE TITLE
NSLayoutConstraint.Attribute and NSLayoutConstraint.Relation issue in Xcode 9.4.1

### ISSUE THREAD

**Issue by ShashikantBhadke** [yonat/MiniLayout#1]
I'm planning to use StepProgressView. In that I found the issue.
NSLayoutConstraint.Attribute replace with NSLayoutAttribute and
NSLayoutConstraint.Relation replace with NSLayoutRelation
This may help some one.
Thanks for all libraries 👍

**Comment by yonat** [comment]
You can use version 1.2.1 of MiniLayout, or upgrade to Xcode 10.
